### ISSUE TITLE
NtDeviceIoControlFile vs DeviceIoControl

### ISSUE THREAD

**Issue by carllerche** [FXTi/iocp-wrapper#11]
Question for @piscisaureus, docs for [`NtDeviceIoControlFile`](https://docs.microsoft.com/en-us/windows/desktop/api/winternl/nf-winternl-ntdeviceiocontrolfile) indicate that the fn is deprecated in favor of [`DeviceIoControl`](https://docs.microsoft.com/en-us/windows/desktop/api/ioapiset/nf-ioapiset-deviceiocontrol). Does this apply to us?

**Comment by piscisaureus** [comment]
@carllerche I think "deprecated" here means "we added a win32 wrapper, please use that from now on".
`NtDeviceIoControlFile` isn't going away anytime soon (or ever). Use whatever is easier.
