### ISSUE TITLE
Translation between IOCP & AFD event flags

### ISSUE THREAD

**Issue by FXTi** [FXTi/iocp-wrapper#13]
From https://github.com/FXTi/iocp-wrapper/issues/5#issuecomment-504661003

Now I realize that the actual event flag used is AFD event flags, and there's code processing the translation(`sock__afd_events_to_epoll_events()`). 

I think that should be useful, so I will impl it.

**Comment by FXTi** [comment]
Mostly done, keep this issue open for potential comments.

**Comment by carllerche** [comment]
Based on [this comment](https://github.com/FXTi/iocp-wrapper/issues/14#issuecomment-504680668). I believe we are going to avoid a conversion step. Instead, we have two structs that wrap the AFD data directly:

- `Interests`
- `Event`

Both of these structs have fns on it that will work directly on the AFD representation.

**Comment by FXTi** [comment]
That's ideal and is the reason why this issue is kept open.

Will do that when https://github.com/FXTi/iocp-wrapper/issues/14 gets started.

**Comment by FXTi** [comment]
Done, conversion is completed in `Selector::feed_events()` and related with `Event`
